version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - article-api-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: article-api
    container_name: article-api
    working_dir: /app
    env_file:
    - .env
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - article-api-network

networks:
  article-api-network:
    driver: bridge